mickey_desktop_apt_packages:
  - cifs-utils
  - docker-compose-v2
  - docker.io
  - qemu-guest-agent
  - samba
  - ubuntu-desktop-minimal
  - xrdp
  - xorgxrdp

mickey_desktop_share_mount_path: /srv/share
mickey_desktop_share_name: mickey-share
mickey_desktop_share_workgroup: WORKGROUP
