mickey_control_apt_packages:
  - age
  - ansible
  - git
  - make
  - openssh-client
  - python3-pip
  - python3-yaml
  - qemu-guest-agent
  - unzip

mickey_terraform_version: "1.14.8"
mickey_sops_version: "3.12.2"
