terraform:
    proxmox_api_url: ENC[AES256_GCM,data:spPE8KwXJYRx/2R8pOm7dGvj/cWEk5twKPOumxIFie20yw==,iv:dlSCYv04/pjywxP0TUuQgLxS3QBUqm44o+nzSORobv4=,tag:AciqZdUk10GxU3CqBMBkPQ==,type:str]
    proxmox_api_token: ENC[AES256_GCM,data:0vH/aPAHo2yhGi9I+wdai9ypvn+YYM2fv5ZqQZZKMrLMOlW/BbKhPqgIOsMliJ2SxU5dAy0EXg==,iv:thqNb7hGZSd7S6JzsDmVq68iz3+wKEXlJ4wqJ+694L0=,tag:NWPtjpbcoDuFOxrmCANApA==,type:str]
    proxmox_tls_insecure: ENC[AES256_GCM,data:It4Kng==,iv:GJKD/lcO30YtQTyuNtchsEjASSrlyrP70qQHsb3Rogk=,tag:aNKKrpucNVIOcaaymi3FmQ==,type:bool]
guests:
    ssh_public_keys:
        - ENC[AES256_GCM,data:OFkxzWEJYO4BSHGDxy3Gys0uaa/C6qNiJcxuD1wijxSUM2rhSzICzH2qHgPOr4BoTJVuA74kiwhZW9qYzUrrauk3sMNVqkY0MVPSvyubM9UzOjG6LmlTZDvzaB7/mg==,iv:kB8QYbDBzv4mgZRJjq3YsL1bW4u04suotHNm1io23xA=,tag:EVFxKaY0Yzn6O6ylkoZkIA==,type:str]
    desktop_admin_password_hash: ENC[AES256_GCM,data:C28437tVzF13GKphGiSaLAHbsAIofCryyupYC1+yD07aSMDAzW6l+uAZjpgrJzM1n9REtX0EHGwlDzAbuXmSmTb0VoceTiYGR2m3D7hiNGcSyzPMtzkPoOk3DRq8uMQuzKV8fCvuXhn3VA==,iv:Pa4ey/PKsi6HldeoooB5e9IAzruGVIaIwExEO2y/uOA=,tag:Ufbk+r3rpUJGxOEXa1xpOg==,type:str]
    control_admin_password_hash: ENC[AES256_GCM,data:JDfI6imAyPW51XJZ14pMpj8o6qbhcovtIQXiS5IDM/MrTYXmx9BsIs3MiVY+GT8OTieYfi2N5nvsnWurrjGOYh6KwuZbQut1g0XxlBZB7lIvN9iqsJA2GSRJbXaemminQMoMpJBPvSUutg==,iv:jxu3yZBMwB0CSo92rNoQla/eZwBsQ+7/JYwK0AZNgjA=,tag:Y4BiEQKmsD7xc/MTfLOQjA==,type:str]
samba:
    username: ENC[AES256_GCM,data:X0iCNt7URZY=,iv:F+GPH5csIwKEEorqPg8MwTEiNFbNt4dY4e7T9avkNGo=,tag:NcRV/ubRybODGRl8PZLvNQ==,type:str]
    password: ENC[AES256_GCM,data:MZyS3XPyZOs=,iv:Kqbpr1J8U9470c2mogQTM0eT/83FCO7KhypFL1l1zVE=,tag:ZcJsDFTd1EnznJEhwwaJ/A==,type:str]
sops:
    age:
        - recipient: age16j0fxm76v5cvtymk6ay3xytew2greqdxsvsyy2ex3tsfukwkuayqejrxur
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WFVoS0VNMzFmV0E3bS9o
            aWdOQ1dJRVJHSDhGR1dEeGp3N0hrVDZLTEVzCk02aWNvY0pEZEVROHVtcWxZTll4
            MVhxVGdOK1YzL0I2L1Z3ZHBveCtXdGsKLS0tIGl4eDlwdk10VWhma2xlVkRPZWJM
            WjFOQnVKdEdjTWhPZXJMdzI5Yll6cDQKHvgs6sPDxw0/KhrtGGhCie2Jpk5fJSJI
            nAf3gx92uJYnMWn+T28golfTaU9yHPjqwi0tNlgaZ+7aXMONwVp2Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T16:15:55Z"
    mac: ENC[AES256_GCM,data:duInsFBFnbjvqVYLqB2FP0S06JEBXc0OMTWyRh0gfS5qyz+7HI9ngeyfedod/AqoBICqzvMLi9hz7XDEg6J4z2hDca80PYOW+2jCau/BrH5Rvj5AUkCe6GRf2LU6xHv6Li8X6XBfdB9bzKRnHWPI10hAS0wNEIFknzdR034cCLA=,iv:cxrEMSoK6Mx6g21GoAgP7aDnukKJ3JNhF6Cn0ogs1XU=,tag:5LgFklwSSnX7OIjLk0ulRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
