terraform:
  proxmox_api_url: "https://10.25.1.101:8006/api2/json"
  proxmox_api_token: "root@pam!terraform=replace-me"
  proxmox_tls_insecure: false

guests:
  ssh_public_keys:
    - "ssh-ed25519 AAAA... replace-me"
  extra_vm_admin_password_hash: "$6$replace-me"
  desktop_admin_password_hash: "$6$replace-me"
  control_admin_password_hash: "$6$replace-me"

samba:
  username: "galvanic"
  password: "replace-me"
